//! Stable names for native AST root trace events.
//!
//! This module is the contract boundary between the parsed AST surface and the
//! planner trace. The strings are intentionally stable because downstream
//! diagnostics and tests use them to compare native handoff behaviour.

use helix_ast::traversal::AstNode;

#[cfg(test)]
mod tests;

pub(super) fn ast_root_kind(root: &AstNode) -> &'static str {
    match root {
        AstNode::Context => "context",
        AstNode::Nodes { .. } => "nodes",
        AstNode::NodesWhere { .. } => "nodes_where",
        AstNode::Edges { .. } => "edges",
        AstNode::EdgesWhere { .. } => "edges_where",
        AstNode::VectorSearchNodes { .. } => "vector_search_nodes",
        AstNode::TextSearchNodes { .. } => "text_search_nodes",
        AstNode::VectorSearchEdges { .. } => "vector_search_edges",
        AstNode::TextSearchEdges { .. } => "text_search_edges",
        AstNode::VectorSearchNodesWithin { .. } => "vector_search_nodes_within",
        AstNode::VectorSearchEdgesWithin { .. } => "vector_search_edges_within",
        AstNode::TextSearchNodesWithin { .. } => "text_search_nodes_within",
        AstNode::TextSearchEdgesWithin { .. } => "text_search_edges_within",
        AstNode::Out { .. } => "out",
        AstNode::In { .. } => "in",
        AstNode::Both { .. } => "both",
        AstNode::OutE { .. } => "out_e",
        AstNode::InE { .. } => "in_e",
        AstNode::BothE { .. } => "both_e",
        AstNode::OutN { .. } => "out_n",
        AstNode::InN { .. } => "in_n",
        AstNode::OtherN { .. } => "other_n",
        AstNode::Has { .. } => "has",
        AstNode::HasLabel { .. } => "has_label",
        AstNode::HasKey { .. } => "has_key",
        AstNode::Where { .. } => "where",
        AstNode::Dedup { .. } => "dedup",
        AstNode::Within { .. } => "within",
        AstNode::Without { .. } => "without",
        AstNode::EdgeHas { .. } => "edge_has",
        AstNode::EdgeHasLabel { .. } => "edge_has_label",
        AstNode::Limit { .. } => "limit",
        AstNode::Skip { .. } => "skip",
        AstNode::Range { .. } => "range",
        AstNode::As { .. } => "as",
        AstNode::Store { .. } => "store",
        AstNode::Select { .. } => "select",
        AstNode::Bind { .. } => "bind",
        AstNode::Inject { input: None, .. } => "inject_source",
        AstNode::Inject { input: Some(_), .. } => "inject",
        AstNode::Count { .. } => "count",
        AstNode::Exists { .. } => "exists",
        AstNode::Id { .. } => "id",
        AstNode::Label { .. } => "label",
        AstNode::Values { .. } => "values",
        AstNode::ValueMap { .. } => "value_map",
        AstNode::Project { .. } => "project",
        AstNode::ProjectBindings { .. } => "project_bindings",
        AstNode::EdgeProperties { .. } => "edge_properties",
        AstNode::CreateIndex { .. } => "create_index",
        AstNode::DropIndex { .. } => "drop_index",
        AstNode::GetIndexOperation { .. } => "get_index_operation",
        AstNode::RetryIndexOperation { .. } => "retry_index_operation",
        AstNode::AbortIndexOperation { .. } => "abort_index_operation",
        AstNode::ShortestPath { .. } => "shortest_path",
        AstNode::AddN { input: None, .. } => "add_node_source",
        AstNode::AddN { input: Some(_), .. } => "add_node",
        AstNode::AddE { .. } => "add_edge",
        AstNode::SetProperty { .. } => "set_property",
        AstNode::RemoveProperty { .. } => "remove_property",
        AstNode::Drop { .. } => "drop",
        AstNode::DropEdge { .. } => "drop_edge",
        AstNode::DropEdgeLabeled { .. } => "drop_edge_labeled",
        AstNode::DropEdgeById { input: None, .. } => "drop_edge_by_id_source",
        AstNode::DropEdgeById { input: Some(_), .. } => "drop_edge_by_id",
        AstNode::OrderBy { .. } => "order_by",
        AstNode::OrderByMultiple { .. } => "order_by_multiple",
        AstNode::Repeat { .. } => "repeat",
        AstNode::Union { .. } => "union",
        AstNode::Choose { .. } => "choose",
        AstNode::Coalesce { .. } => "coalesce",
        AstNode::Optional { .. } => "optional",
        AstNode::Group { .. } => "group",
        AstNode::GroupCount { .. } => "group_count",
        AstNode::AggregateBy { .. } => "aggregate_by",
        AstNode::Fold { .. } => "fold",
        AstNode::Unfold { .. } => "unfold",
        AstNode::Path { .. } => "path",
        AstNode::SimplePath { .. } => "simple_path",
        AstNode::WithSack { .. } => "with_sack",
        AstNode::SackSet { .. } => "sack_set",
        AstNode::SackAdd { .. } => "sack_add",
        AstNode::SackGet { .. } => "sack_get",
    }
}
